### ISSUE TITLE
Discuss about project structure

### ISSUE THREAD

**Issue by ms-dehghani** [ms-dehghani/android-marvel-comics#3]
In this issue we should discuss about project structure and layer communication

**Comment by pariami** [comment]
For the structure of the project, we are going to proceed according to MVVM and Clean architecture, so for this we need a data layer, domain and presentation, and since we want to have a modular project, we need to create the data layer and the domain as separate modules. In addition to the fact that we are going to get the data from the Marvel API, we want to have a mock layer inside the data layer.
And that based on the features we have in the project (one movie list and one movie detail) inside each of the modules we must have a directory for each feature.

**Comment by ms-dehghani** [comment]
It's ok. how about communication between layer's. for instance for connecting domain to data wee need some interfaces. what's those interfaces and what methods they have? 
for instance detail screen may need interfaces like bellow:

 fun MovieItem getMoveDetail(String movieID)

and list screen may need some thing like this:

fun MovieListItem getMovieList(int pageNumber)
or   
fun MovieListItem getMovieList(String lastFetchedMovieID , int count)

**Comment by pariami** [comment]
I did not understand exactly what you mean. Well, the interfaces are placed in the domain layer and we implement these interfaces for the repository in the data layer. And the domain layer also uses usecases to access the data layer. Do you mean something else?

**Comment by pariami** [comment]
we can use this method :

// domain layer
interface MovieRepository {
    fun getMovies(): Flow<PagingData<Movie>>
}

// data layer
class MovieRepositoryImpl(
    private val movieDataSource: MovieDataSource
) : MovieRepository {
    override fun getMovies(): Flow<PagingData<Movie>> {
        return Pager(
            config = PagingConfig(pageSize = 20),
            pagingSourceFactory = { movieDataSource }
        ).flow
    }
}

// domain layer
class GetMoviesUseCase(
    private val movieRepository: MovieRepository
) {
    fun getMovies(): Flow<PagingData<Movie>> {
        return movieRepository.getMovies()
    }
}

// data layer
class MovieDataSource(
    private val movieService: MovieService
) : PagingSource<Int, Movie>() {
    override suspend fun load(params: LoadParams<Int>): LoadResult<Int, Movie> {
        val page = params.key ?: 1
        val response = movieService.getPopularMovies(page)
        val movies = response.results
        val prevKey = if (page == 1) null else page - 1
        val nextKey = if (movies.isEmpty()) null else page + 1
        return LoadResult.Page(
            data = movies,
            prevKey = prevKey,
            nextKey = nextKey
        )
    }
}
load() function returns a LoadResult.Page object that contains the loaded data, as well as the previous and next keys for pagination.
